//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeldCutList
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutList
    {
        public string Folder_Name { get; set; }
        public string Body_Name { get; set; }
        public string MaterialProperty { get; set; }
    }
}
